//
// Created by Winter Cyan on 2020/6/7.
//

#ifndef DISTRIBUTEDMQ_PARAM_HPP
#define DISTRIBUTEDMQ_PARAM_HPP

#define DEFAULT_DEST_QM "QM3"
#define CHAR_SET "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
#define MSG_SZ 40
#define QM_NAME_SZ 20

enum MCA_STATUS {RUNNING, SUSPENDED, STOPPED};


#endif //DISTRIBUTEDMQ_PARAM_HPP
